import {
  AutonomousRun,
  AutonomousRunSchedule,
  BrokerAdapterStatus,
  BrokerFill,
  BrokerSnapshot,
  BudgetEnvelope,
  InvestmentProposal,
  OrderPlanApproval,
  PaperAccountEvent,
  PaperOrderPlan,
  ResearchRun,
  RiskEvaluation,
  RunScheduleWorkerStatus,
} from "../../types";

export const DOCUMENTED_BUDGET_ENVELOPES: BudgetEnvelope[] = [
  {
    id: "budget-docs-dry-run",
    name: "Documented aggressive dry-run budget",
    status: "active",
    mode: "dry_run",
    currency: "KRW",
    totalBudget: 10_000_000,
    cashReservePct: 20,
    allowedAssetClasses: ["cash", "domestic_stock", "domestic_etf"],
    policy: {
      maxGrossExposurePct: 100,
      maxSinglePositionPct: 20,
      maxOrderNotional: 1_000_000,
      maxDailyLossPct: 3,
      maxDrawdownPct: 10,
      maxDataAgeMinutes: 60,
      allowedAssetClasses: ["cash", "domestic_stock", "domestic_etf"],
      allowLiveTrading: false,
      requireHumanApproval: true,
    },
    brokerExecutionEnabled: false,
    liveTradingEnabled: false,
    notes: "Documented sample budget for dashboard fallback.",
    createdAt: "2026-05-22T08:20:00.000Z",
    updatedAt: "2026-05-22T08:20:00.000Z",
  },
];

export const DOCUMENTED_RESEARCH_RUNS: ResearchRun[] = [
  {
    id: "rr-docs-momentum-001",
    budgetEnvelopeId: "budget-docs-dry-run",
    objective: "Validate a dry-run momentum baseline before any proposal",
    strategyFamily: "cross-sectional momentum",
    hypothesis:
      "Liquid domestic equities with stronger 60-day risk-adjusted returns outperform the benchmark after simple cost assumptions.",
    status: "proposal_ready",
    phase: "artifacts_persisted",
    advanceEligible: true,
    datasetRefs: [
      {
        id: "krx-daily-bars",
        source: "documented-sample",
        windowStart: "2024-01-01",
        windowEnd: "2026-05-21",
        availabilityTimestamp: "2026-05-21T23:50:00.000Z",
      },
    ],
    featureRefs: ["return_60d", "volatility_20d", "turnover_rank"],
    timestampLagRules: ["Signals use data available before proposal time."],
    noLookaheadChecked: true,
    benchmark: "KOSPI 200 total return proxy",
    costModel: "10 bps per side plus exchange fees",
    slippageModel: "5 bps spread haircut on entries and exits",
    modelName: "deterministic-ranking-baseline",
    validationWindow: {
      start: "2025-05-22",
      end: "2026-05-21",
    },
    backtestMetrics: {
      totalReturnPct: 11.8,
      benchmarkReturnPct: 7.2,
      maxDrawdownPct: 8.9,
      sharpeRatio: 1.14,
      turnoverPct: 138,
      tradeCount: 42,
    },
    artifactRefs: ["s3://research-runs/docs/momentum-001/report.json"],
    artifactHashes: {
      "s3://research-runs/docs/momentum-001/report.json": "sha256:sample",
    },
    knownFailureModes: [
      "Momentum reversal during high-volatility regimes",
      "Capacity constraints in lower-liquidity names",
    ],
    brokerExecutionEnabled: false,
    liveTradingEnabled: false,
    createdAt: "2026-05-22T08:30:00.000Z",
    updatedAt: "2026-05-22T08:42:00.000Z",
  },
];

export const DOCUMENTED_INVESTMENT_PROPOSALS: InvestmentProposal[] = [
  {
    id: "proposal-docs-momentum-001",
    budgetEnvelopeId: "budget-docs-dry-run",
    researchRunId: "rr-docs-momentum-001",
    strategyId: "momentum-v1",
    ruleId: "long-only-breakout",
    actor: "strategy",
    status: "paper_ready",
    generatedAt: "2026-05-22T09:00:00.000Z",
    marketDataTimestamp: "2026-05-22T08:55:00.000Z",
    portfolioSnapshot: {
      currency: "KRW",
      equity: 10_000_000,
      cash: 10_000_000,
      grossExposurePct: 0,
      positions: [],
    },
    orders: [
      {
        symbol: "005930",
        assetClass: "domestic_stock",
        side: "BUY",
        orderType: "MARKET",
        notional: 500_000,
        targetPositionPct: 5,
      },
    ],
    thesis: "Documented momentum allocation after reproducible backtest.",
    evidenceRefs: ["s3://research-runs/docs/momentum-001/report.json"],
    brokerExecutionEnabled: false,
    requiresHumanApproval: false,
    createdAt: "2026-05-22T09:00:00.000Z",
    updatedAt: "2026-05-22T09:03:00.000Z",
  },
];

export const DOCUMENTED_RISK_EVALUATIONS: RiskEvaluation[] = [
  {
    id: "risk-docs-001",
    proposalId: "proposal-docs-momentum-001",
    decision: "ALLOW",
    reasons: ["Paper-mode order stays inside documented policy limits."],
    requestSnapshot: {
      mode: "paper",
      actor: "strategy",
      researchRunId: 1,
      strategyId: "momentum-v1",
      ruleId: "long-only-breakout",
      generatedAt: "2026-05-22T09:00:00.000Z",
      marketDataTimestamp: "2026-05-22T08:55:00.000Z",
      portfolio: {
        currency: "KRW",
        equity: 10_000_000,
        cash: 10_000_000,
        grossExposurePct: 0,
        positions: [],
      },
      orders: DOCUMENTED_INVESTMENT_PROPOSALS[0].orders,
      evidenceRefs: ["s3://research-runs/docs/momentum-001/report.json"],
      executionIntent: "evaluate_only",
    },
    responseSnapshot: {
      decision: "ALLOW",
      evaluatedAt: "2026-05-22T09:02:00.000Z",
      mode: "paper",
      brokerExecutionEnabled: false,
      requiresHumanApproval: false,
      reasons: ["Paper-mode order stays inside documented policy limits."],
      policy: DOCUMENTED_BUDGET_ENVELOPES[0].policy,
      approvedOrderCount: 1,
    },
    brokerExecutionEnabled: false,
    requiresHumanApproval: false,
    evaluatedAt: "2026-05-22T09:02:00.000Z",
    createdAt: "2026-05-22T09:02:00.000Z",
  },
];

export const DOCUMENTED_AUTONOMOUS_RUNS: AutonomousRun[] = [
  {
    id: "run-docs-001",
    objective: "Autonomously prepare a dry-run allocation from budget",
    status: "risk_checked",
    currentStage: "risk_evaluated",
    budgetEnvelopeId: "budget-docs-dry-run",
    researchRunId: "rr-docs-momentum-001",
    proposalId: "proposal-docs-momentum-001",
    riskEvaluationId: "risk-docs-001",
    timeline: [
      {
        at: "2026-05-22T08:50:00.000Z",
        stage: "idle",
        message: "Run created. Waiting for research and proposal generation.",
      },
      {
        at: "2026-05-22T08:52:00.000Z",
        stage: "researching",
        message:
          "Research run rr-docs-momentum-001 finished with status proposal_ready.",
      },
      {
        at: "2026-05-22T08:54:00.000Z",
        stage: "proposed",
        message: "Proposal proposal-docs-momentum-001 generated with 1 order.",
      },
      {
        at: "2026-05-22T08:55:00.000Z",
        stage: "risk_checked",
        message: "Risk evaluation risk-docs-001 returned ALLOW.",
      },
    ],
    lastAction: "Risk evaluation risk-docs-001 returned ALLOW",
    nextAction:
      "Wait for signed paper approval and active paper account before execution",
    createdAt: "2026-05-22T08:50:00.000Z",
    updatedAt: "2026-05-22T08:55:00.000Z",
  },
];

export const DOCUMENTED_AUTONOMOUS_RUN_SCHEDULES: AutonomousRunSchedule[] = [
  {
    id: "schedule-docs-001",
    budgetEnvelopeId: "budget-docs-dry-run",
    objective: "Tick documented autonomous dry-run allocation",
    mode: "dry_run",
    cadenceMinutes: 60,
    nextRunAt: "2026-05-22T09:50:00.000Z",
    enabled: true,
    attemptPaperExecution: false,
    lastRunId: "run-docs-001",
    lastCycleKey: "schedule:schedule-docs-001:2026-05-22T08:50:00.000Z",
    lastTickAt: "2026-05-22T08:50:00.000Z",
    leaseOwner: null,
    leaseExpiresAt: null,
    lastError: null,
    brokerExecutionEnabled: false,
    liveTradingEnabled: false,
    createdAt: "2026-05-22T08:45:00.000Z",
    updatedAt: "2026-05-22T08:55:00.000Z",
  },
];

export const DOCUMENTED_RUN_SCHEDULE_WORKER_STATUS: RunScheduleWorkerStatus = {
  enabled: false,
  cron: "*/1 * * * *",
  workerId: "documented-worker",
  maxSchedulesPerTick: 5,
  leaseTtlSeconds: 120,
  currentTime: "2026-05-22T08:55:00.000Z",
  lastTickAt: "2026-05-22T08:50:00.000Z",
  lastResult: {
    trigger: "documented",
    workerId: "documented-worker",
    enabled: false,
    startedAt: "2026-05-22T08:50:00.000Z",
    completedAt: "2026-05-22T08:50:00.000Z",
    scanned: 0,
    ticked: 0,
    failed: 0,
    skipped: 0,
    items: [],
  },
};

export const DOCUMENTED_BROKER_ADAPTER_STATUS: BrokerAdapterStatus = {
  provider: "toss",
  configured: false,
  readOnlyEnabled: false,
  paperTradingEnabled: false,
  liveTradingEnabled: false,
  authMethod: "oauth2_client_credentials",
  credentialRef: "missing",
  credentialCustody: {
    mode: "missing",
    configured: false,
    productionReady: false,
    secretRef: "missing",
    detail:
      "Production trading requires an external secret manager reference before broker write access can be considered.",
  },
  schemaVerified: false,
  sandboxVerified: false,
  readOnlyPoll: {
    provider: "toss",
    enabled: false,
    configured: false,
    schemaVerified: false,
    canPoll: false,
    baseUrl: "https://openapi.tossinvest.com",
    accountRef: "missing",
    allowedEndpoints: [
      "POST /oauth2/token",
      "GET /api/v1/accounts",
      "GET /v1/holdings",
    ],
    cron: "*/5 * * * *",
    running: false,
    lastReconciliationStatus: "not_checked",
    brokerExecutionEnabled: false,
    liveTradingEnabled: false,
  },
  capabilities: [
    {
      key: "credentials",
      status: "blocked",
      detail:
        "TOSS_OPEN_API_CLIENT_ID, TOSS_OPEN_API_CLIENT_SECRET, and TOSS_OPEN_API_ACCOUNT_REF are required.",
    },
    {
      key: "credentialCustody",
      status: "blocked",
      detail:
        "Production trading requires an external secret manager reference before broker write access can be considered.",
    },
    {
      key: "openApiSchema",
      status: "blocked",
      detail: "Exact Toss OpenAPI schema is not verified in this repo.",
    },
    {
      key: "readOnlyAccountSnapshot",
      status: "blocked",
      detail:
        "Read-only polling remains disabled until credentials, schema, and BROKER_READ_ONLY_ENABLED=true are present.",
    },
    {
      key: "orderPlacement",
      status: "blocked",
      detail:
        "Live order placement is intentionally blocked until read-only reconciliation, sandbox parity, approval custody, and kill switch runtime exist.",
    },
  ],
  blockers: [
    "credentials: Toss Open API credentials are missing.",
    "openApiSchema: Exact Toss OpenAPI schema is not verified.",
    "orderPlacement: Live order placement is intentionally blocked.",
  ],
  brokerExecutionEnabled: false,
};

export const DOCUMENTED_PAPER_ORDER_PLANS: PaperOrderPlan[] = [
  {
    id: "paper-docs-plan-001",
    proposalId: "proposal-docs-momentum-001",
    researchRunId: "rr-docs-momentum-001",
    budgetEnvelopeId: "budget-docs-dry-run",
    riskEvaluationId: "risk-docs-001",
    orderPlanApprovalId: "approval-docs-001",
    proposalHash: "sha256:docs-proposal",
    riskRequestHash: "sha256:docs-risk",
    planHash: "sha256:docs-plan",
    idempotencyKey: "docs-paper-plan-001",
    status: "reconciled",
    mode: "paper",
    submittedAt: "2026-05-22T09:05:00.000Z",
    completedAt: "2026-05-22T09:06:00.000Z",
    readinessSnapshot: {
      budgetActive: true,
      latestRiskAllow: true,
      riskMatchesProposal: true,
      paperEngineEnabled: true,
      brokerExecutionDisabled: true,
      liveTradingDisabled: true,
      explicitPaperAccountActive: true,
      killSwitchArmed: true,
      killSwitchTripped: false,
      cashSufficient: true,
      positionsSufficient: true,
      noDuplicatePlan: true,
      requiredCash: 500_750,
      reservedCash: 0,
      availableCash: 10_000_000,
      requiredSellNotionalBySymbol: {},
      reservedSellNotionalBySymbol: {},
      availableSellNotionalBySymbol: {},
    },
    reservationHold: {
      holdId: "paper-reservation:docs:001",
      status: "consumed",
      idempotencyKey: "docs-paper-plan-001",
      createdAt: "2026-05-22T09:05:00.000Z",
      consumedAt: "2026-05-22T09:05:00.000Z",
      cashAmount: 500_750,
      sellNotionalBySymbol: {},
      availableCashAtHold: 10_000_000,
      availableSellNotionalBySymbolAtHold: {},
      holdHash: "sha256:docs-reservation-hold",
      notes: ["Consumed by documented paper order plan."],
    },
    orders: [
      {
        paperOrderId: "paper-order:docs:0",
        proposalOrderIndex: 0,
        symbol: "005930",
        side: "BUY",
        orderType: "MARKET",
        requestedNotional: 500_000,
        targetPositionPct: 5,
        marketDataTimestamp: "2026-05-22T09:00:00.000Z",
        feeModelRef: "fixed-10bps-paper-fee-v1",
        slippageModelRef: "fixed-5bps-paper-slippage-v1",
        sourceOrder: {
          symbol: "005930",
          assetClass: "domestic_stock",
          side: "BUY",
          orderType: "MARKET",
          notional: 500_000,
          targetPositionPct: 5,
        },
      },
    ],
    fills: [
      {
        paperFillId: "paper-order:docs:0:fill:0",
        paperOrderId: "paper-order:docs:0",
        timestamp: "2026-05-22T09:05:00.000Z",
        symbol: "005930",
        side: "BUY",
        quantity: 6.8,
        fillPrice: 73_500,
        grossNotional: 499_850,
        requestedNotional: 500_000,
        filledNotional: 499_850,
        fee: 500,
        feeCurrency: "KRW",
        slippage: 150,
        netCashDelta: -500_500,
        positionDelta: 6.8,
        averagePriceBefore: 73_500,
        costBasisBefore: 0,
        costBasisAfter: 500_650,
        realizedPnl: 0,
        realizedPnlAfter: 0,
        status: "filled",
      },
    ],
    portfolioBefore: {
      currency: "KRW",
      equity: 10_000_000,
      cash: 10_000_000,
      grossExposurePct: 0,
    },
    portfolioAfter: {
      currency: "KRW",
      equity: 9_999_850,
      cash: 9_499_500,
      grossExposurePct: 5,
    },
    cashLedger: [
      {
        paperCashEventId: "paper-order:docs:0:fill:0:cash",
        paperFillId: "paper-order:docs:0:fill:0",
        timestamp: "2026-05-22T09:05:00.000Z",
        currency: "KRW",
        amount: -500_500,
        balanceAfter: 9_499_500,
        reason: "BUY paper fill net cash delta",
      },
    ],
    positionLedger: [
      {
        paperPositionEventId: "paper-order:docs:0:fill:0:position",
        paperFillId: "paper-order:docs:0:fill:0",
        timestamp: "2026-05-22T09:05:00.000Z",
        symbol: "005930",
        quantityDelta: 6.8,
        notionalDelta: 499_850,
        quantityAfter: 6.8,
        positionNotionalAfter: 499_850,
        averagePriceAfter: 73_625,
        costBasisAfter: 500_650,
        realizedPnl: 0,
      },
    ],
    startingCash: 10_000_000,
    endingCash: 9_499_500,
    startingEquity: 10_000_000,
    endingEquity: 9_999_850,
    brokerExecutionEnabled: false,
    liveTradingEnabled: false,
    reconciliation: {
      status: "matched",
      reconciledAt: "2026-05-22T09:06:00.000Z",
      cashMatched: true,
      positionsMatched: true,
      expectedCash: 9_499_500,
      actualCash: 9_499_500,
      cashDiff: 0,
      expectedPositions: { "005930": 499_850 },
      actualPositions: { "005930": 499_850 },
      positionDiffs: { "005930": 0 },
      tolerance: 0.01,
      notes: ["Paper cash ledger matched simulated fills."],
    },
    killSwitchSnapshot: {
      armed: true,
      tripped: false,
      checkedAt: "2026-05-22T09:05:00.000Z",
      reason: "Execution control state is active.",
    },
    blockedReasons: [],
    createdAt: "2026-05-22T09:04:00.000Z",
    updatedAt: "2026-05-22T09:06:30.000Z",
  },
];

export const DOCUMENTED_ORDER_PLAN_APPROVALS: OrderPlanApproval[] = [
  {
    id: "approval-docs-001",
    proposalId: "proposal-docs-momentum-001",
    budgetEnvelopeId: "budget-docs-dry-run",
    riskEvaluationId: "risk-docs-001",
    idempotencyKey: "docs-paper-plan-001",
    mode: "paper",
    approver: "documented-operator",
    reason: "Approve documented paper execution sample.",
    status: "consumed",
    proposalHash: "sha256:docs-proposal",
    riskRequestHash: "sha256:docs-risk",
    approvalHash: "sha256:docs-approval",
    approvalSnapshot: {
      proposalId: 1,
      riskEvaluationId: 1,
      mode: "paper",
      approver: "documented-operator",
      reason: "Approve documented paper execution sample.",
      idempotencyKey: "docs-paper-plan-001",
      approvedOrderCount: 1,
      approvedAt: "2026-05-22T09:03:00.000Z",
      proposalHash: "sha256:docs-proposal",
      riskRequestHash: "sha256:docs-risk",
    },
    approvedAt: "2026-05-22T09:03:00.000Z",
    consumedAt: "2026-05-22T09:05:00.000Z",
    consumedByPaperOrderPlanId: "paper-docs-plan-001",
    brokerExecutionEnabled: false,
    liveTradingEnabled: false,
    createdAt: "2026-05-22T09:03:00.000Z",
    updatedAt: "2026-05-22T09:05:00.000Z",
  },
];

export const DOCUMENTED_PAPER_ACCOUNT_EVENTS: PaperAccountEvent[] = [
  {
    id: "paper-account-event-docs-003",
    paperAccountId: "paper-account-docs-001",
    budgetEnvelopeId: "budget-docs-dry-run",
    eventType: "paper_order_plan",
    sourceId: "paper-docs-plan-001",
    idempotencyKey: "paper-account-plan:paper-docs-plan-001",
    actor: "paper-execution-engine",
    reason: "Applied documented paper order plan.",
    sequence: 3,
    currency: "KRW",
    cashBefore: 10_000_000,
    cashAfter: 9_499_500,
    equityBefore: 10_000_000,
    equityAfter: 9_999_850,
    cashDelta: -500_500,
    equityDelta: -150,
    previousEventHash: "sha256:docs-account-promote",
    requestHash: "sha256:docs-account-plan-request",
    eventHash: "sha256:docs-account-plan",
    eventSnapshot: {
      paperAccountId: 1,
      budgetEnvelopeId: 1,
      eventType: "paper_order_plan",
      sourceId: 1,
      idempotencyKey: "paper-account-plan:paper-docs-plan-001",
      actor: "paper-execution-engine",
      reason: "Applied documented paper order plan.",
      sequence: 3,
      currency: "KRW",
      cashBefore: 10_000_000,
      cashAfter: 9_499_500,
      equityBefore: 10_000_000,
      equityAfter: 9_999_850,
      positionsBefore: [],
      positionsAfter: [
        {
          symbol: "005930",
          assetClass: "domestic_stock",
          marketValue: 499_850,
          weightPct: 5,
          quantity: 6.8,
          averagePrice: 73_625,
          costBasis: 500_650,
          unrealizedPnl: -800,
          realizedPnl: 0,
        },
      ],
      previousEventHash: "sha256:docs-account-promote",
      requestHash: "sha256:docs-account-plan-request",
      recordedAt: "2026-05-22T09:05:00.000Z",
    },
    brokerExecutionEnabled: false,
    liveTradingEnabled: false,
    createdAt: "2026-05-22T09:05:00.000Z",
  },
  {
    id: "paper-account-event-docs-002",
    paperAccountId: "paper-account-docs-001",
    budgetEnvelopeId: "budget-docs-dry-run",
    eventType: "account_promoted",
    idempotencyKey: "docs-paper-account-promote-001",
    actor: "documented-operator",
    reason: "Promote explicitly seeded paper capital for execution.",
    sequence: 2,
    currency: "KRW",
    cashBefore: 10_000_000,
    cashAfter: 10_000_000,
    equityBefore: 10_000_000,
    equityAfter: 10_000_000,
    cashDelta: 0,
    equityDelta: 0,
    previousEventHash: "sha256:docs-account-seed",
    requestHash: "sha256:docs-account-promote-request",
    eventHash: "sha256:docs-account-promote",
    eventSnapshot: {
      paperAccountId: 1,
      budgetEnvelopeId: 1,
      eventType: "account_promoted",
      idempotencyKey: "docs-paper-account-promote-001",
      actor: "documented-operator",
      reason: "Promote explicitly seeded paper capital for execution.",
      sequence: 2,
      currency: "KRW",
      cashBefore: 10_000_000,
      cashAfter: 10_000_000,
      equityBefore: 10_000_000,
      equityAfter: 10_000_000,
      positionsBefore: [],
      positionsAfter: [],
      previousEventHash: "sha256:docs-account-seed",
      requestHash: "sha256:docs-account-promote-request",
      recordedAt: "2026-05-22T09:00:00.000Z",
    },
    brokerExecutionEnabled: false,
    liveTradingEnabled: false,
    createdAt: "2026-05-22T09:00:00.000Z",
  },
  {
    id: "paper-account-event-docs-001",
    paperAccountId: "paper-account-docs-001",
    budgetEnvelopeId: "budget-docs-dry-run",
    eventType: "explicit_seed",
    idempotencyKey: "docs-paper-account-seed-001",
    actor: "documented-operator",
    reason: "Explicitly seed paper capital before execution.",
    sequence: 1,
    currency: "KRW",
    cashBefore: 0,
    cashAfter: 10_000_000,
    equityBefore: 0,
    equityAfter: 10_000_000,
    cashDelta: 10_000_000,
    equityDelta: 10_000_000,
    requestHash: "sha256:docs-account-seed-request",
    eventHash: "sha256:docs-account-seed",
    eventSnapshot: {
      paperAccountId: 1,
      budgetEnvelopeId: 1,
      eventType: "explicit_seed",
      idempotencyKey: "docs-paper-account-seed-001",
      actor: "documented-operator",
      reason: "Explicitly seed paper capital before execution.",
      sequence: 1,
      currency: "KRW",
      cashBefore: 0,
      cashAfter: 10_000_000,
      equityBefore: 0,
      equityAfter: 10_000_000,
      positionsBefore: [],
      positionsAfter: [],
      requestHash: "sha256:docs-account-seed-request",
      recordedAt: "2026-05-22T08:55:00.000Z",
    },
    brokerExecutionEnabled: false,
    liveTradingEnabled: false,
    createdAt: "2026-05-22T08:55:00.000Z",
  },
];

export const DOCUMENTED_BROKER_SNAPSHOTS: BrokerSnapshot[] = [
  {
    id: "broker-snapshot-docs-001",
    provider: "manual",
    sourceRef: "documented-read-only-import",
    accountRefHash: "sha256:docs-account-ref",
    status: "matched",
    currency: "KRW",
    cash: 9_499_500,
    equity: 9_999_850,
    grossExposurePct: 5,
    positions: [
      {
        symbol: "005930",
        assetClass: "domestic_stock",
        marketValue: 499_850,
        weightPct: 5,
        quantity: 6.8,
        averagePrice: 73_625,
        costBasis: 500_650,
        unrealizedPnl: -800,
        realizedPnl: 0,
      },
    ],
    asOf: "2026-05-22T09:07:00.000Z",
    reconciliation: {
      status: "matched",
      checkedAt: "2026-05-22T09:08:00.000Z",
      paperAccountId: "paper-account-docs-001",
      cashMatched: true,
      equityMatched: true,
      positionsMatched: true,
      expectedPaperCash: 9_499_500,
      actualBrokerCash: 9_499_500,
      cashDiff: 0,
      expectedPaperEquity: 9_999_850,
      actualBrokerEquity: 9_999_850,
      equityDiff: 0,
      expectedPaperPositions: { "005930": 499_850 },
      actualBrokerPositions: { "005930": 499_850 },
      positionDiffs: { "005930": 0 },
      tolerance: 0.01,
      maxAgeMinutes: 60,
      notes: ["Read-only broker snapshot matched the paper account sample."],
    },
    brokerExecutionEnabled: false,
    liveTradingEnabled: false,
    createdAt: "2026-05-22T09:07:00.000Z",
    updatedAt: "2026-05-22T09:08:00.000Z",
  },
];

export const DOCUMENTED_BROKER_FILLS: BrokerFill[] = [
  {
    id: "broker-fill-docs-001",
    provider: "manual",
    sourceRef: "documented-read-only-fill-import",
    accountRefHash: "sha256:docs-account-ref",
    brokerOrderRefHash: "sha256:docs-broker-order",
    brokerFillRefHash: "sha256:docs-broker-fill",
    status: "imported",
    symbol: "005930",
    side: "BUY",
    quantity: 6.8,
    fillPrice: 73_500,
    grossNotional: 499_800,
    fee: 500,
    feeCurrency: "KRW",
    currency: "KRW",
    filledAt: "2026-05-22T09:06:00.000Z",
    asOf: "2026-05-22T09:07:00.000Z",
    reconciliation: {
      status: "not_checked",
      symbolMatched: false,
      sideMatched: false,
      quantityMatched: false,
      notionalMatched: false,
      feeMatched: false,
      brokerQuantity: 6.8,
      brokerGrossNotional: 499_800,
      brokerFee: 500,
      tolerance: 0.01,
      notes: ["Documented read-only broker fill evidence sample."],
    },
    brokerExecutionEnabled: false,
    liveTradingEnabled: false,
    createdAt: "2026-05-22T09:07:00.000Z",
    updatedAt: "2026-05-22T09:07:00.000Z",
  },
];
