import { BrokerSnapshot, PaperOrderPlan, ResearchRun } from "../../types";

export const DOCUMENTED_RESEARCH_RUNS: ResearchRun[] = [
  {
    id: "rr-docs-momentum-001",
    budgetEnvelopeId: "budget-docs-dry-run",
    objective: "Validate a dry-run momentum baseline before any proposal",
    strategyFamily: "cross-sectional momentum",
    hypothesis:
      "Liquid domestic equities with stronger 60-day risk-adjusted returns outperform the benchmark after simple cost assumptions.",
    status: "proposal_ready",
    phase: "artifacts_persisted",
    advanceEligible: true,
    datasetRefs: [
      {
        id: "krx-daily-bars",
        source: "documented-sample",
        windowStart: "2024-01-01",
        windowEnd: "2026-05-21",
        availabilityTimestamp: "2026-05-21T23:50:00.000Z",
      },
    ],
    featureRefs: ["return_60d", "volatility_20d", "turnover_rank"],
    timestampLagRules: ["Signals use data available before proposal time."],
    noLookaheadChecked: true,
    benchmark: "KOSPI 200 total return proxy",
    costModel: "10 bps per side plus exchange fees",
    slippageModel: "5 bps spread haircut on entries and exits",
    modelName: "deterministic-ranking-baseline",
    validationWindow: {
      start: "2025-05-22",
      end: "2026-05-21",
    },
    backtestMetrics: {
      totalReturnPct: 11.8,
      benchmarkReturnPct: 7.2,
      maxDrawdownPct: 8.9,
      sharpeRatio: 1.14,
      turnoverPct: 138,
      tradeCount: 42,
    },
    artifactRefs: ["s3://research-runs/docs/momentum-001/report.json"],
    artifactHashes: {
      "s3://research-runs/docs/momentum-001/report.json": "sha256:sample",
    },
    knownFailureModes: [
      "Momentum reversal during high-volatility regimes",
      "Capacity constraints in lower-liquidity names",
    ],
    brokerExecutionEnabled: false,
    liveTradingEnabled: false,
    createdAt: "2026-05-22T08:30:00.000Z",
    updatedAt: "2026-05-22T08:42:00.000Z",
  },
];

export const DOCUMENTED_PAPER_ORDER_PLANS: PaperOrderPlan[] = [
  {
    id: "paper-docs-plan-001",
    proposalId: "proposal-docs-momentum-001",
    researchRunId: "rr-docs-momentum-001",
    budgetEnvelopeId: "budget-docs-dry-run",
    riskEvaluationId: "risk-docs-001",
    proposalHash: "sha256:docs-proposal",
    riskRequestHash: "sha256:docs-risk",
    planHash: "sha256:docs-plan",
    idempotencyKey: "docs-paper-plan-001",
    status: "reconciled",
    mode: "paper",
    submittedAt: "2026-05-22T09:05:00.000Z",
    completedAt: "2026-05-22T09:06:00.000Z",
    readinessSnapshot: {
      budgetActive: true,
      latestRiskAllow: true,
      riskMatchesProposal: true,
      paperEngineEnabled: true,
      brokerExecutionDisabled: true,
      liveTradingDisabled: true,
      killSwitchArmed: true,
      killSwitchTripped: false,
      cashSufficient: true,
      positionsSufficient: true,
      noDuplicatePlan: true,
    },
    orders: [
      {
        paperOrderId: "paper-order:docs:0",
        proposalOrderIndex: 0,
        symbol: "005930",
        side: "BUY",
        orderType: "MARKET",
        requestedNotional: 500_000,
        targetPositionPct: 5,
        marketDataTimestamp: "2026-05-22T09:00:00.000Z",
        feeModelRef: "fixed-10bps-paper-fee-v1",
        slippageModelRef: "fixed-5bps-paper-slippage-v1",
        sourceOrder: {
          symbol: "005930",
          assetClass: "domestic_stock",
          side: "BUY",
          orderType: "MARKET",
          notional: 500_000,
          targetPositionPct: 5,
        },
      },
    ],
    fills: [
      {
        paperFillId: "paper-order:docs:0:fill:0",
        paperOrderId: "paper-order:docs:0",
        timestamp: "2026-05-22T09:05:00.000Z",
        symbol: "005930",
        side: "BUY",
        quantity: 6.8,
        fillPrice: 73_500,
        grossNotional: 499_850,
        requestedNotional: 500_000,
        filledNotional: 499_850,
        fee: 500,
        feeCurrency: "KRW",
        slippage: 150,
        netCashDelta: -500_500,
        positionDelta: 6.8,
        status: "filled",
      },
    ],
    portfolioBefore: {
      currency: "KRW",
      equity: 10_000_000,
      cash: 10_000_000,
      grossExposurePct: 0,
    },
    portfolioAfter: {
      currency: "KRW",
      equity: 9_999_850,
      cash: 9_499_500,
      grossExposurePct: 5,
    },
    cashLedger: [
      {
        paperCashEventId: "paper-order:docs:0:fill:0:cash",
        paperFillId: "paper-order:docs:0:fill:0",
        timestamp: "2026-05-22T09:05:00.000Z",
        currency: "KRW",
        amount: -500_500,
        balanceAfter: 9_499_500,
        reason: "BUY paper fill net cash delta",
      },
    ],
    positionLedger: [
      {
        paperPositionEventId: "paper-order:docs:0:fill:0:position",
        paperFillId: "paper-order:docs:0:fill:0",
        timestamp: "2026-05-22T09:05:00.000Z",
        symbol: "005930",
        quantityDelta: 6.8,
        notionalDelta: 499_850,
        positionNotionalAfter: 499_850,
      },
    ],
    startingCash: 10_000_000,
    endingCash: 9_499_500,
    startingEquity: 10_000_000,
    endingEquity: 9_999_850,
    brokerExecutionEnabled: false,
    liveTradingEnabled: false,
    reconciliation: {
      status: "matched",
      reconciledAt: "2026-05-22T09:06:00.000Z",
      cashMatched: true,
      positionsMatched: true,
      expectedCash: 9_499_500,
      actualCash: 9_499_500,
      cashDiff: 0,
      expectedPositions: { "005930": 499_850 },
      actualPositions: { "005930": 499_850 },
      positionDiffs: { "005930": 0 },
      tolerance: 0.01,
      notes: ["Paper cash ledger matched simulated fills."],
    },
    killSwitchSnapshot: {
      armed: true,
      tripped: false,
      checkedAt: "2026-05-22T09:05:00.000Z",
      reason: "Execution control state is active.",
    },
    blockedReasons: [],
    createdAt: "2026-05-22T09:04:00.000Z",
    updatedAt: "2026-05-22T09:06:30.000Z",
  },
];

export const DOCUMENTED_BROKER_SNAPSHOTS: BrokerSnapshot[] = [
  {
    id: "broker-snapshot-docs-001",
    provider: "manual",
    sourceRef: "documented-read-only-import",
    accountRefHash: "sha256:docs-account-ref",
    status: "matched",
    currency: "KRW",
    cash: 9_499_500,
    equity: 9_999_850,
    grossExposurePct: 5,
    positions: [
      {
        symbol: "005930",
        assetClass: "domestic_stock",
        marketValue: 499_850,
        weightPct: 5,
      },
    ],
    asOf: "2026-05-22T09:07:00.000Z",
    reconciliation: {
      status: "matched",
      checkedAt: "2026-05-22T09:08:00.000Z",
      paperAccountId: "paper-account-docs-001",
      cashMatched: true,
      equityMatched: true,
      positionsMatched: true,
      expectedPaperCash: 9_499_500,
      actualBrokerCash: 9_499_500,
      cashDiff: 0,
      expectedPaperEquity: 9_999_850,
      actualBrokerEquity: 9_999_850,
      equityDiff: 0,
      expectedPaperPositions: { "005930": 499_850 },
      actualBrokerPositions: { "005930": 499_850 },
      positionDiffs: { "005930": 0 },
      tolerance: 0.01,
      maxAgeMinutes: 60,
      notes: ["Read-only broker snapshot matched the paper account sample."],
    },
    brokerExecutionEnabled: false,
    liveTradingEnabled: false,
    createdAt: "2026-05-22T09:07:00.000Z",
    updatedAt: "2026-05-22T09:08:00.000Z",
  },
];
