name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: [gigio1023-arc-runner-set]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install backend dependencies
        run: npm ci
        working-directory: backend
      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and deploy containers
        run: docker compose up -d --build

